[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
qbitflow_payment_system = "48xuDnaYoAgo7dEZaJUt5xxrkfUYBbySWBWwNrydHEhU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# wallet = "~/.config/solana/id.json"
wallet = "target/deploy/qbitflow_payment_system-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
