[workspace]
members = [
    "programs/*",
	# "targets/*",
	# "tests/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
codegen-units = 1
opt-level = "z"
lto = "fat"
# lto = 1
panic = "abort"
strip = "symbols"

[profile.release.build-override]
# opt-level = 3
incremental = false
